"""Fallback language metadata for parser plugins.

The primary source of this data is the parser plugin's WIT ``language-info``
export.  These defaults keep older plugins and currently-built Wasm artifacts
usable while plugin authors adopt the richer contract.
"""

from __future__ import annotations

from intentdiff.core.models import LanguagePluginInfo

_BUILTIN_LAST_UPDATED = "2026-05-19"

_MONACO: dict[str, str] = {
    "bash": "shell",
    "c": "c",
    "clojure": "clojure",
    "cpp": "cpp",
    "csharp": "csharp",
    "css": "css",
    "dart": "dart",
    "dockerfile": "dockerfile",
    "elixir": "elixir",
    "go": "go",
    "groovy": "groovy",
    "haskell": "haskell",
    "html": "html",
    "java": "java",
    "javascript": "javascript",
    "json": "json",
    "kotlin": "kotlin",
    "lua": "lua",
    "markdown": "markdown",
    "mdx": "markdown",
    "perl": "perl",
    "php": "php",
    "powershell": "powershell",
    "python": "python",
    "py": "python",
    "r": "r",
    "ruby": "ruby",
    "rust": "rust",
    "scala": "scala",
    "scss": "scss",
    "sql": "sql",
    "swift": "swift",
    "terraform": "hcl",
    "typescript": "typescript",
    "tsx": "typescript",
    "xml": "xml",
    "yaml": "yaml",
    "yml": "yaml",
}

_DEFAULT_FILENAMES: dict[str, str] = {
    "abap": "code.abap",
    "adf": "pipeline.json",
    "asm": "code.asm",
    "assemblyscript": "code.as",
    "astro": "Page.astro",
    "bash": "code.sh",
    "c": "code.c",
    "clojure": "code.clj",
    "cpp": "code.cpp",
    "csharp": "Code.cs",
    "css": "style.css",
    "dart": "code.dart",
    "databricks-workflow": "workflow.yml",
    "dax": "measure.dax",
    "dbt-sql": "model.sql",
    "dbt-yaml": "schema.yml",
    "delphi": "code.pas",
    "dockerfile": "Dockerfile",
    "elixir": "code.ex",
    "freebasic": "code.bas",
    "generic": "code.txt",
    "gitignore": ".gitignore",
    "graphql": "schema.graphql",
    "go": "code.go",
    "groovy": "code.groovy",
    "haskell": "code.hs",
    "html": "index.html",
    "java": "Code.java",
    "javascript": "code.js",
    "json": "data.json",
    "kotlin": "Code.kt",
    "asciidoc": "README.adoc",
    "latex": "paper.tex",
    "lua": "code.lua",
    "m": "query.m",
    "markdown": "README.md",
    "toml": "config.toml",
    "ini": "settings.ini",
    "gomod": "go.mod",
    "make": "Makefile",
    "proto": "service.proto",
    "cmake": "CMakeLists.txt",
    "mdx": "doc.mdx",
    "ocaml": "code.ml",
    "odin": "code.odin",
    "perl": "code.pl",
    "php": "code.php",
    "plsql": "code.sql",
    "po": "messages.po",
    "postscript": "code.ps",
    "powershell": "code.ps1",
    "puppet": "site.pp",
    "python": "code.py",
    "qsharp": "Program.qs",
    "r": "code.r",
    "reasonml": "component.re",
    "ruby": "code.rb",
    "rust": "code.rs",
    "sas": "code.sas",
    "scala": "Code.scala",
    "scss": "style.scss",
    "sql": "code.sql",
    "squirrel": "code.nut",
    "svelte": "Component.svelte",
    "swift": "code.swift",
    "terraform": "main.tf",
    "tsx": "component.tsx",
    "typescript": "code.ts",
    "vbnet": "Code.vb",
    "vue": "Component.vue",
    "wat": "module.wat",
    "xml": "data.xml",
    "yaml": "data.yaml",
    "zig": "code.zig",
}

_EXTENSIONS: dict[str, list[str]] = {
    "python": [".py", ".pyi"],
    "javascript": [".js", ".mjs", ".cjs", ".jsx"],
    "typescript": [".ts", ".mts", ".cts"],
    "tsx": [".tsx"],
    "sql": [".sql", ".ddl", ".dml"],
    "dbt-sql": [".sql"],
    "dbt-yaml": [".yml", ".yaml"],
    "yaml": [".yml", ".yaml"],
    "json": [".json"],
    "m": [".m"],
    "markdown": [".md", ".markdown", ".mdown", ".mkd", ".mkdn"],
    "toml": [".toml"],
    "ini": [".ini", ".cfg", ".conf", ".editorconfig", ".gitconfig"],
    "gomod": ["go.mod"],
    "make": ["Makefile", "GNUmakefile", ".mk", ".make"],
    "proto": [".proto"],
    "cmake": ["CMakeLists.txt", ".cmake"],
    "html": [".html", ".htm"],
    "graphql": [".graphql", ".gql"],
    "gitignore": [
        ".gitignore",
        ".dockerignore",
        ".npmignore",
        ".eslintignore",
        ".prettierignore",
        ".helmignore",
        ".gcloudignore",
        ".cursorignore",
        ".vscodeignore",
    ],
    "latex": [".tex", ".latex"],
    "asciidoc": [".adoc", ".asciidoc", ".asc"],
    "ocaml": [".ml", ".mli"],
    "po": [".po", ".pot"],
    "reasonml": [".re", ".rei"],
    "css": [".css"],
    "scss": [".scss"],
    "xml": [".xml"],
    "terraform": [".tf", ".hcl"],
    "dockerfile": ["Dockerfile"],
}

_DISPLAY_NAMES: dict[str, tuple[str, str]] = {
    "adf": ("Azure Data Factory", "ADF"),
    "asm": ("Assembly", "ASM"),
    "csharp": ("C#", "C#"),
    "cpp": ("C++", "C++"),
    "dbt-sql": ("dbt SQL", "dbt SQL"),
    "dbt-yaml": ("dbt YAML", "dbt YAML"),
    "asciidoc": ("AsciiDoc", "AsciiDoc"),
    "gitignore": ("Ignore file", "Ignore"),
    "graphql": ("GraphQL", "GraphQL"),
    "latex": ("LaTeX", "LaTeX"),
    "ocaml": ("OCaml", "OCaml"),
    "po": ("PO/gettext", "PO"),
    "reasonml": ("ReasonML", "ReasonML"),
    "dax": ("DAX", "DAX"),
    "m": ("Power Query M", "M"),
    "markdown": ("Markdown", "Markdown"),
    "toml": ("TOML", "TOML"),
    "ini": ("INI", "INI"),
    "gomod": ("go.mod", "gomod"),
    "make": ("Makefile", "make"),
    "proto": ("Protocol Buffers", "proto"),
    "cmake": ("CMake", "CMake"),
    "mdx": ("MDX", "MDX"),
    "plsql": ("PL/SQL", "PL/SQL"),
    "qsharp": ("Q#", "Q#"),
    "tsx": ("TSX", "TSX"),
    "tsql": ("T-SQL", "T-SQL"),
    "vbnet": ("VB.NET", "VB.NET"),
    "wat": ("WebAssembly Text", "WAT"),
}


def _title(language_id: str) -> tuple[str, str]:
    if language_id in _DISPLAY_NAMES:
        return _DISPLAY_NAMES[language_id]
    words = language_id.replace("_", "-").split("-")
    name = " ".join(word.upper() if len(word) <= 3 else word.title() for word in words)
    return name, name


def fallback_language_info(
    language_id: str,
    *,
    plugin_id: str,
    grammar_id: str,
    priority: int,
    is_trusted: bool,
    provenance: str,
    author: str = "",
    plugin_version: str = "",
    last_updated: str = "",
) -> LanguagePluginInfo:
    """Return best-effort metadata for a language handled by a parser plugin."""

    language_name, short_name = _title(language_id)
    default_filename = _DEFAULT_FILENAMES.get(language_id, f"code.{language_id}")
    extensions = _EXTENSIONS.get(language_id)
    if extensions is None and "." in default_filename:
        extensions = ["." + default_filename.rsplit(".", 1)[1]]
    return LanguagePluginInfo(
        language_id=language_id,
        language_name=language_name,
        language_short_name=short_name,
        monaco_language=_MONACO.get(language_id, "plaintext"),
        default_filename=default_filename,
        language_file_extensions=extensions or [],
        author=author,
        plugin_version=plugin_version,
        last_updated=last_updated or (_BUILTIN_LAST_UPDATED if is_trusted else ""),
        plugin_id=plugin_id,
        grammar_id=grammar_id,
        priority=priority,
        is_trusted=is_trusted,
        provenance=provenance,
    )
