"""intentdiff.serve._app
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

FastAPI application for the Online Diff Playground and public API.

Endpoints
---------
GET  /             — Monaco-editor web UI (HTML)
GET  /languages    — JSON list of all supported language IDs
POST /diff         — Compute semantic diff between two code strings
GET  /api/docs     — OpenAPI / Swagger UI (auto-generated by FastAPI)
"""

from __future__ import annotations

import asyncio
import re
from pathlib import Path
from typing import Annotated, Any

from fastapi import FastAPI, HTTPException, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, HTMLResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, ConfigDict, Field, field_validator

from intentdiff import DiffConfig, SemanticDiffer, StringSource
from intentdiff.plugins.exceptions import GrammarNotInstalledError, PluginNotFoundError

_MAX_CONTENT_BYTES = 512 * 1024     # 512 KB per pane
_MAX_REQUEST_BODY_BYTES = 8 * 1024 * 1024  # 8 MB total envelope
_HTML_PATH = Path(__file__).parent / "_static" / "index.html"
_STATIC_DIR = Path(__file__).parent / "_static"
_VENDOR_DIR = _STATIC_DIR / "vendor"

# Content-Security-Policy for the playground.
# worker-src 'self' blob: is required for Monaco web workers.
# style-src 'unsafe-inline' is required for Monaco inline styles.
# When Monaco is fully vendored no external origins are needed.
_CSP = (
    "default-src 'self'; "
    "script-src 'self'; "
    "worker-src 'self' blob:; "
    "connect-src 'self'; "
    "img-src 'self' data:; "
    "style-src 'self' 'unsafe-inline';"
)

# Language IDs: start with alphanumeric, then alphanumeric/hyphen/dot/underscore, max 64 chars.
_LANG_RE = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,63}$")
_PLUGIN_ID_RE = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9_.:-]{0,127}$")
_MAX_CANDIDATES = 50
_MAX_CANDIDATE_BYTES = 64


def _request_body_too_large_response() -> Response:
    limit_mb = _MAX_REQUEST_BODY_BYTES // (1024 * 1024)
    return Response(
        f'{{"detail": "Request body too large (max {limit_mb} MB)"}}',
        status_code=413,
        media_type="application/json",
    )


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------


class DiffRequest(BaseModel):
    """Body for POST /diff."""

    model_config = ConfigDict(extra="forbid")

    old: Annotated[str, Field(description="Old file content (\u2264 512 KB)")]
    new: Annotated[str, Field(description="New file content (\u2264 512 KB)")]
    filename: str = Field(
        default="code.py",
        description="Filename used for language auto-detection (no path separators).",
    )
    language: str | None = Field(
        default=None,
        description="Explicit language hint — overrides filename-based detection.",
    )

    plugin_id: str | None = Field(
        default=None,
        description="Opaque parser plugin ID from GET /language-info.",
    )

    @field_validator("language")
    @classmethod
    def _validate_language(cls, v: str | None) -> str | None:
        if v is not None and not _LANG_RE.fullmatch(v):
            raise ValueError(
                "language must be 1-64 alphanumeric/hyphen/dot/underscore characters"
            )
        return v

    @field_validator("plugin_id")
    @classmethod
    def _validate_plugin_id(cls, v: str | None) -> str | None:
        if v is not None and not _PLUGIN_ID_RE.fullmatch(v):
            raise ValueError(
                "plugin_id must be 1-128 alphanumeric/hyphen/dot/underscore/colon characters"
            )
        return v

    @field_validator("old", "new")
    @classmethod
    def _limit_size(cls, v: str) -> str:
        if len(v.encode()) > _MAX_CONTENT_BYTES:
            raise ValueError(
                f"Content exceeds {_MAX_CONTENT_BYTES // 1024} KB limit"
            )
        return v

    @field_validator("filename")
    @classmethod
    def _no_traversal(cls, v: str) -> str:
        if ".." in v or "/" in v or "\\" in v:
            raise ValueError(
                "filename must be a bare name with no path separators or traversal"
            )
        return v


class DetectRequest(BaseModel):
    """Body for POST /detect."""

    model_config = ConfigDict(extra="forbid")

    content: Annotated[str, Field(description="Code snippet to analyse (≤ 512 KB)")]
    candidates: list[str] | None = Field(
        default=None,
        description="Optional shortlist of language IDs from a client-side heuristic.",
    )
    preferred_plugins: dict[str, str] | None = Field(
        default=None,
        description="Optional language -> plugin ID preferences from GET /language-info.",
    )
    plugin_id: str | None = Field(
        default=None,
        description="Optional parser plugin ID from GET /language-info.",
    )

    @field_validator("content")
    @classmethod
    def _limit_size(cls, v: str) -> str:
        if len(v.encode()) > _MAX_CONTENT_BYTES:
            raise ValueError(
                f"Content exceeds {_MAX_CONTENT_BYTES // 1024} KB limit"
            )
        return v

    @field_validator("candidates")
    @classmethod
    def _validate_candidates(cls, v: list[str] | None) -> list[str] | None:
        if v is None:
            return v
        if len(v) > _MAX_CANDIDATES:
            raise ValueError(f"candidates list exceeds {_MAX_CANDIDATES} items")
        for item in v:
            if len(item.encode()) > _MAX_CANDIDATE_BYTES:
                raise ValueError(
                    f"candidate item exceeds {_MAX_CANDIDATE_BYTES} bytes: {item!r}"
                )
            if not _LANG_RE.fullmatch(item):
                raise ValueError(
                    f"invalid candidate language ID {item!r}: must match "
                    r"^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,63}$"
                )
        return v

    @field_validator("preferred_plugins")
    @classmethod
    def _validate_preferred_plugins(
        cls, v: dict[str, str] | None
    ) -> dict[str, str] | None:
        if v is None:
            return v
        if len(v) > _MAX_CANDIDATES:
            raise ValueError(f"preferred_plugins exceeds {_MAX_CANDIDATES} items")
        for language, plugin_id in v.items():
            if not _LANG_RE.fullmatch(language):
                raise ValueError(f"invalid preferred plugin language ID {language!r}")
            if not _PLUGIN_ID_RE.fullmatch(plugin_id):
                raise ValueError(f"invalid preferred plugin ID {plugin_id!r}")
        return v

    @field_validator("plugin_id")
    @classmethod
    def _validate_plugin_id(cls, v: str | None) -> str | None:
        if v is not None and not _PLUGIN_ID_RE.fullmatch(v):
            raise ValueError(f"invalid plugin ID {v!r}")
        return v


def _supported_languages(differ: Any) -> list[str]:
    """Return supported language IDs for the playground picker."""
    provider = getattr(differ, "supported_languages", None)
    if callable(provider):
        result = provider()
        if isinstance(result, list):
            return sorted({lang for lang in result if isinstance(lang, str)})
    return sorted(
        {lang for parser in differ._registry.parsers for lang in parser.language_ids}
    )


def _language_info(differ: Any) -> list[dict[str, Any]]:
    """Return rich language metadata for the playground."""
    provider = getattr(differ, "language_info", None)
    if callable(provider):
        result = provider()
        if isinstance(result, list):
            return [
                item.model_dump(by_alias=True) if hasattr(item, "model_dump") else item
                for item in result
                if isinstance(item, dict) or hasattr(item, "model_dump")
            ]
    return [
        {
            "language": lang,
            "selectedPluginId": lang,
            "plugins": [
                {
                    "languageId": lang,
                    "languageName": lang,
                    "languageShortName": lang,
                    "monacoLanguage": "plaintext",
                    "defaultFilename": f"code.{lang}",
                    "languageFileExtensions": [],
                    "author": "",
                    "pluginVersion": "",
                    "lastUpdated": "",
                    "pluginId": lang,
                    "grammarId": lang,
                    "priority": 0,
                    "isTrusted": False,
                    "provenance": "",
                }
            ],
        }
        for lang in _supported_languages(differ)
    ]


# ---------------------------------------------------------------------------
# App factory
# ---------------------------------------------------------------------------


def create_app(
    config: DiffConfig | None = None,
    differ: Any | None = None,  # SemanticDiffer | test mock
    cors_origins: list[str] | None = None,
) -> FastAPI:
    """Create and return the FastAPI playground application.

    Parameters
    ----------
    config:
        Optional :class:`~intentdiff.DiffConfig`.  Ignored when *differ*
        is supplied directly (useful for tests).
    differ:
        Optional pre-built :class:`~intentdiff.SemanticDiffer` (or any
        object with a ``.diff(source)`` method).  When ``None`` a fresh
        instance is created from *config*.
    cors_origins:
        Explicit list of allowed CORS origins.  When ``None`` (default) no
        CORS middleware is added — the API is not usable cross-origin.
        Pass ``["*"]`` only in development environments behind a firewall.
        Never use ``["*"]`` in production facing untrusted networks.
    """
    cfg = config or DiffConfig()
    _differ: Any = differ if differ is not None else SemanticDiffer(cfg)
    _html = _HTML_PATH.read_text(encoding="utf-8")

    # Semaphore to bound concurrent diff/detect computations.
    _sem = asyncio.Semaphore(8)

    app = FastAPI(
        title="IntentDiff Playground",
        description=(
            "Semantic code diff API.  "
            "`POST /diff` with `{old, new, language}` → SemanticDiff JSON."
        ),
        version="1.0.0",
        docs_url="/api/docs",
        redoc_url=None,
    )

    @app.middleware("http")
    async def _limit_body_size(request: Request, call_next):  # type: ignore[return]
        cl = request.headers.get("content-length")
        if cl is not None:
            try:
                if int(cl) > _MAX_REQUEST_BODY_BYTES:
                    return _request_body_too_large_response()
            except ValueError:
                pass

        chunks: list[bytes] = []
        total = 0
        async for chunk in request.stream():
            total += len(chunk)
            if total > _MAX_REQUEST_BODY_BYTES:
                return _request_body_too_large_response()
            chunks.append(chunk)
        body = b"".join(chunks)
        sent = False

        async def receive():  # type: ignore[no-untyped-def]
            nonlocal sent
            if sent:
                return {"type": "http.request", "body": b"", "more_body": False}
            sent = True
            return {"type": "http.request", "body": body, "more_body": False}

        request._body = body  # type: ignore[attr-defined]
        request._receive = receive  # type: ignore[attr-defined]
        return await call_next(request)

    if cors_origins is not None:
        app.add_middleware(
            CORSMiddleware,
            allow_origins=cors_origins,
            allow_methods=["GET", "POST"],
            allow_headers=["Content-Type", "Accept"],
            max_age=600,
        )

    # Mount vendored static assets (Monaco, etc.).
    # The vendor directory is optional at import time — it is populated by
    # running ``python scripts/vendor_monaco.py`` before serving.
    if _VENDOR_DIR.exists():
        app.mount(
            "/static/vendor",
            StaticFiles(directory=str(_VENDOR_DIR)),
            name="vendor",
        )

    # ── Routes ───────────────────────────────────────────────────────────────

    @app.get("/", response_class=HTMLResponse, include_in_schema=False)
    async def index() -> HTMLResponse:
        return HTMLResponse(content=_html, headers={"Content-Security-Policy": _CSP})

    @app.get("/static/playground.js", include_in_schema=False)
    async def playground_script() -> FileResponse:
        return FileResponse(
            _STATIC_DIR / "playground.js",
            media_type="application/javascript",
        )

    @app.get("/languages", summary="List supported languages")
    async def languages() -> dict[str, list[str]]:
        """Return all language IDs accepted by the ``/diff`` endpoint."""
        return {"languages": _supported_languages(_differ)}

    @app.get("/language-info", summary="List language and parser plugin metadata")
    async def language_info() -> dict[str, list[dict[str, Any]]]:
        """Return grouped language/plugin metadata for the playground UI."""
        return {"languages": _language_info(_differ)}

    @app.post("/diff", summary="Compute semantic diff")
    async def diff(req: DiffRequest) -> Response:
        """Compute a semantic diff between two code strings.

        Returns a **SemanticDiff** JSON object.  The response is stateless —
        no submitted code is stored.
        """
        try:
            async with _sem:
                if req.plugin_id:
                    result = await asyncio.to_thread(
                        _differ.diff_strings,
                        req.old,
                        req.new,
                        req.filename,
                        req.language,
                        parser_plugin_id=req.plugin_id,
                    )
                else:
                    source = StringSource(
                        req.old,
                        req.new,
                        filename=req.filename,
                        language_hint=req.language,
                    )
                    result = await asyncio.to_thread(_differ.diff, source)
        except PluginNotFoundError as exc:
            raise HTTPException(
                status_code=422,
                detail=f"Unknown language: {exc}",
            ) from exc
        except GrammarNotInstalledError as exc:
            raise HTTPException(
                status_code=422,
                detail=str(exc),
            ) from exc
        return Response(
            content=result.model_dump_json(),
            media_type="application/json",
        )

    # ── Detect endpoint ───────────────────────────────────────────────────

    @app.post("/detect", summary="Detect language from content")
    async def detect(req: DetectRequest) -> dict:
        """Return ranked language candidates detected by the registered parsers.

        Each parser's own Wasm ``detect-language`` function is consulted — no
        regex heuristics in Python.  The response is stateless.
        """
        try:
            async with _sem:
                if req.plugin_id:
                    results = await asyncio.to_thread(
                        _differ.detect_all,
                        req.content,
                        req.candidates,
                        req.preferred_plugins,
                        req.plugin_id,
                    )
                elif req.preferred_plugins:
                    results = await asyncio.to_thread(
                        _differ.detect_all,
                        req.content,
                        req.candidates,
                        req.preferred_plugins,
                    )
                else:
                    results = await asyncio.to_thread(
                        _differ.detect_all, req.content, req.candidates
                    )
        except PluginNotFoundError as exc:
            raise HTTPException(
                status_code=422,
                detail=f"Unknown parser plugin: {exc}",
            ) from exc
        top = results[0].language if results else None
        return {
            "language": top,
            "candidates": [
                {"language": r.language, "confidence": r.confidence}
                for r in results[:3]
            ],
        }

    @app.get("/example/{language}", summary="Fetch demo old/new example for a language")
    async def example(language: str, plugin_id: str | None = None) -> dict:
        """Return the ``old`` and ``new`` demo snippets for *language*.

        Each parser plugin supplies its own example via the WIT
        ``playground-example`` function.  Returns ``{"old": null, "new": null}``
        for unknown languages so the client can gracefully clear the editors.
        """
        if not _LANG_RE.fullmatch(language):
            raise HTTPException(
                status_code=422,
                detail="Invalid language identifier. "
                "Must be 1-64 alphanumeric/hyphen/dot/underscore characters.",
            )
        if plugin_id is not None and not _PLUGIN_ID_RE.fullmatch(plugin_id):
            raise HTTPException(
                status_code=422,
                detail="Invalid plugin identifier.",
            )
        try:
            if plugin_id:
                ex = await asyncio.to_thread(_differ.playground_example, language, plugin_id)
            else:
                ex = await asyncio.to_thread(_differ.playground_example, language)
        except PluginNotFoundError as exc:
            raise HTTPException(
                status_code=422,
                detail=f"Unknown parser plugin: {exc}",
            ) from exc
        if ex is None:
            return {"old": None, "new": None}
        return {"old": ex["old"], "new": ex["new"]}

    return app
